version: "3.8"
name: biz-card-prod
services:
  server_prod_s:
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    image: ${SERVER_IMAGE}
    container_name: ${SERVER_CONTAINER}
    command: npm run start
    ports:
      - "4000:4000"
    networks:
      - app-network
  client_prod_s:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    image: ${CLIENT_IMAGE}
    container_name: ${CLIENT_CONTAINER}
    depends_on:
      - server_prod_s
    ports:
      - "80:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  web-root:
    driver: local
